package model;

import oracle.jbo.Key;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Jul 05 14:10:18 CEST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleImpl extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleImpl() {
    }

    /**
     * Container's getter for EmployeesView1.
     * @return EmployeesView1
     */
    public ViewObjectImpl getEmployeesView1() {
        return (ViewObjectImpl) findViewObject("EmployeesView1");
    }

    /**
     * Container's getter for EmployeesView2.
     * @return EmployeesView2
     */
    public ViewObjectImpl getEmployeesView2() {
        return (ViewObjectImpl) findViewObject("EmployeesView2");
    }

    /**
     * Container's getter for EmpManagerFkLink.
     * @return EmpManagerFkLink
     */
    public ViewLinkImpl getEmpManagerFkLink() {
        return (ViewLinkImpl) findViewLink("EmpManagerFkLink");
    }
    /**
     * Helper method to return an Employee by Id
     */
    private EmployeesImpl retrieveEmployeeById(Integer employeeId) {
      EntityDefImpl employeesDef = EmployeesImpl.getDefinitionObject();
      Key orderKey = EmployeesImpl.createPrimaryKey(employeeId);
      return (EmployeesImpl) employeesDef.findByPrimaryKey(getDBTransaction(), orderKey);
    }

    /**
     * Find an Employee and its Manager
     */
    public String findEmployeeAndManager(Integer employeeId) {
      EmployeesImpl employee = retrieveEmployeeById(employeeId);
      if (employee != null) {
        EmployeesImpl manager = retrieveEmployeeById(employee.getManagerId());
        if (manager != null) {
          return 
              "Employee: " + employee.getLastName() + ", " + employee.getFirstName() + 
              ", Manager: " + employee.getLastName() + ", " + employee.getFirstName();
        } else {
          return "Unassigned";
        }
      } else {
        return null;
      }
    }
}

